### ISSUE TITLE
MCD installation failed

### ISSUE THREAD

**Issue by cyl123789** [SamuelBroughton/StarGAN-Voice-Conversion#1]
MCD installation failed

**Comment by shackysureshot** [comment]
Hi @cyl123789 could your possibly provide more information on your issue?

**Comment by cyl123789** [comment]
Thank you, I have solved it

**Comment by cyl123789** [comment]
100%|██████████| 109/109 [00:00<00:00, 1316.80it/s]
  0%|          | 0/109 [00:00<?, ?it/s]concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "D:\Users\Administrator\anaconda3\envs\tensorflow\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "D:\workspace\StarGAN最新版\StarGAN-Voice-Conversion-master\preprocess.py", line 30, in resample
    subprocess.call(['sox', wav_from, '-r', str(sampling_rate), wav_to])
  File "D:\Users\Administrator\anaconda3\envs\tensorflow\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Users\Administrator\anaconda3\envs\tensorflow\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "D:\Users\Administrator\anaconda3\envs\tensorflow\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

But I had this problem in the pre-processing

**Comment by shackysureshot** [comment]
Looks like you're getting a file not found for SoX, have you installed it?

**Comment by cyl123789** [comment]
Which one should I download



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samuel Broughton"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 下午4:29
收件人: "SamuelBroughton/StarGAN-Voice-Conversion"<StarGAN-Voice-Conversion@noreply.github.com&gt;; 
抄送: "白衣沽酒琦罗生"<2928848893@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [SamuelBroughton/StarGAN-Voice-Conversion] MCD installation failed (#1)





 
似乎您找不到针对SoX的文件，是否已安装？
 
- 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by cyl123789** [comment]
![image](https://user-images.githubusercontent.com/29319485/83500526-74179e80-a4f1-11ea-89e8-14cb50f6076f.png)

Which one should I download

**Comment by shackysureshot** [comment]
From your previous error message it looks like you're using windows.

**Comment by shackysureshot** [comment]
FYI - I have not tested any of this repository on windows
